#by Abhinav Mishra
#Flavours of python
#1.Cpython-currently using
#2.Jython- python - java
#IronPython- dotnet liabraries

#versions - 2.x vs 3.x
# syntax - print "hello" vs print("hello")

"""
Python Date-23/01/24
<-------------------->

    Desktop App -> Tkinter,Kivy,PyQts,wxPython
    web application -> Flask, Django, Pyramid
    Mobile appication-> Kivy 
    Testing-> pytest, robot framework, selenium
    Automation-> paramiko
    Data Science -> 
    Data Analytics -> NumPy,Pandas,Matplotlib, Seaborn
    Liabraries to implement necessary algorithms
    Data Engineering-> Kafka , Zookeeper, Java, C, C++, RUBY,Python, Spark,Hadoop
    ML -> Deep learning, NLP.
    AI -> 
    R Programming ->competition of Python.

Mathematics ,Stats
<------------------->

Python
-------
1.SDK- minimum libs to execute the py code
2.Shell- Interactive Environment
3.IDLE - Integrated Dev Environment
    
--> Why Python is a scripting tool than a programming language?
1.Python is a interpreted language.
2.data types is dynamic declared at run time.


Operator Overloading
--------------------
1. +-> addition and concantenatiom
2. *-> multiplication operator

Numbers
-------
integers
long
float
complex

Strings
--------

Boolean
-------



CUDA Library- to run code on gpu

COMMAND TO RUN FILE FORM IDLE TO CMD PROMPT
import os
os.getcwd() "to get the curr working directory u will get add
os.chdir("add of the file") "chdir is to change the cwd"
import filename.py
from imp import reload " to reuse the code again and again"
reload(filename)


CODING RULES:
-------------->
#! c:python\bin

print("Hello)
#!=shebang gives you the path of executable form.

COMMENTS= # IS SINGLE LINE COMMENT

Strings
------->
Single line string Stored in " " or '' no difference 
multiplie line stirng """ """" or'''  '''

Ctrl+D will copy the duplicate selected lines
Ctrl+ "\" will comment many lines

WE DONT USE PARANTHESIS
------------------------->
1.if condition
2.loops
3.functions and classes

We use indentation(a tab key)

use cotrol +shift +alt +l to format the code

OPERATORS
--------->
Arithmatic operators->
Comparison  or relational->
Logical ->
Bitwise->
Turnary->

Loops
------
1.for loop - is like for each loop
            - for loop depends on a collection and his collection is generated by Range function
2.while loop

Print function
--------------
print(data,sep=,end=\n)

Primitive DatType
------------------>

Stirng
------>
1.they are immutable in python
-11-10-9-8-7-6  -5 -4 -3 -2 -1 0
 h  e  l  l  o     w  o  r  l  d
 0  1  2  3  4  5  6  7  8  9  10

 
 PYTHON DATASTRUCTURES: Date-25/jan/2024
 ---------------------->
 -Lists
 -dictionary
 -Tuple
 -Set

 Lists:
 ------>
1.collection of a hetrogenous data (different type of data types)
2. memory allocation is not contigious.
3.orderd collection of data
4.static memory allocation
5.subscritable
6.lists are enclosed in a [].

List maniputlation function:
append,extend,copy,count,insert,pop,reverse , clear,sort
1.append can add only one element in the list and at the end.

Dictionary
---------->
1.its an associative array.
2.its an ordered collection.
3.dictionaries are mutable
4.deictionaries are enclosed in {k1:v1,k2:v2,k3:v3}

'a','b','c','d','e'
 0   1   2   3   4

0:a,1:b,2:c,3:d,4:e
0,1,2,3,4->keys
a b c d e->>values
1.keys are always unique
2.keys are user defined
3.values can be another element,list or dictionary

#functions to mainpulate:clear ,copy,fromkeys,get,keys,pop,popitem,sedefault,update,values

tupples : are immutable list
are enclosed in ()

Sets
----->
1.elements of set is unique
2.not iterable
3.unorderd collection


Funcitons
--------->
Pass by value -                                                                  pass by refrence-
1.working on immutable objects                                                   2.work on mutable object.

Scope of a variable
global
local
non local

date and time library
https://notepad.pw/kpitBatch 

-----------------------------------------------------------------------------------------------------

Private,Public,Protected
------------------------>
private variable- __pvtVar
protected variable - __proVar
public= publicVar


File Handling->
txt files-ascii format
open a file in a specific mode
read-r
write-w->you have to delete the exsisting data and then you can write.
append-a->you can add data to the file

class FrenchDeck:
    ranks = [str(n) for n in range(2, 11)] + ['J', 'Q', 'K', 'A']
    suits = ['spades', 'diamonds', 'clubs', 'hearts']

    def __init__(self):
        self.cards = [(number, shape) for shape in self.suits
                      for number in self.ranks]

    def __len__(self):
        return len(self.cards)

    def __getitem__(self, location):
        return self.cards[location]
deck = FrenchDeck()

n=int(input("Enter the number to print :"
print(f"Cards:{deck[n]}")


import a python file as module
1.py file will get converted into .pyc  file and stored in a folder
2.python will check for .pth file in your native directory (where python.exe is present)
3.checks for the library pathb that is  present in the sys.path
4.checks for the date and time of creation of .py vs .pyc files.Expects the .pyc file to have the latest date or time of modification\

venv 
    Lib
        kpi_package
            __init__.py
            kpit.py

python -m filename.
create a file with extension .pth

Sorting Techniques
------------------>
1.bubble sort
2.quick sort
3.insertion sort
4.selection sort
5.merge sort
6.heap sort

Linked List:
-------------
1.single ll
2.double ll
3.circular ll

GUI for Python:
--------------
1.PyQt5
2.Tkinter
3.Kivy
4.wxPython
5.Libavg
6.PySimpleGui
7.PyForms
8.Eax
9.PySlide2
10.PyGui

windows
    |
Xwindows
_____________
c,c++,python,pearl,ruby

TCL->Tool command language using the TCL they developed TK->Tool Kit when this integrated with python it gives TKinter

task - take a audio file audio1 and audio2 and we have to compare them 

pip install tk
pip install pillow
pip install pygame

"""
